import type { Folder, Item, Release } from '@/types'

export const SEED_FOLDERS: Folder[] = [
  { is_duplicatable: false, id: 'folder-admissions', name: 'Admissions', parent_id: null, tags: ['ADMISSIONS', 'CORE'], sort_order: 1 },
  { is_duplicatable: false, id: 'folder-adm-forms', name: 'Application Forms', parent_id: 'folder-admissions', tags: ['FORMS'], sort_order: 1 },
  { is_duplicatable: false, id: 'folder-adm-workflow', name: 'Workflow & Stages', parent_id: 'folder-admissions', tags: ['WORKFLOW'], sort_order: 2 },
  { is_duplicatable: false, id: 'folder-adm-docs', name: 'Document Checklist', parent_id: 'folder-admissions', tags: ['DOCS'], sort_order: 3 },

  { is_duplicatable: false, id: 'folder-events', name: 'Events', parent_id: null, tags: ['EVENTS', 'CORE'], sort_order: 2 },
  { is_duplicatable: false, id: 'folder-events-reg', name: 'Event Registration', parent_id: 'folder-events', tags: ['REGISTRATION'], sort_order: 1 },
  { is_duplicatable: false, id: 'folder-events-email', name: 'Email Templates', parent_id: 'folder-events', tags: ['EMAIL'], sort_order: 2 },

  { is_duplicatable: false, id: 'folder-crm', name: 'CRM', parent_id: null, tags: ['CRM', 'CORE'], sort_order: 3 },
  { is_duplicatable: false, id: 'folder-crm-contacts', name: 'Contacts', parent_id: 'folder-crm', tags: ['CONTACTS'], sort_order: 1 },
  { is_duplicatable: false, id: 'folder-crm-pipeline', name: 'Pipeline', parent_id: 'folder-crm', tags: ['PIPELINE'], sort_order: 2 },

  { is_duplicatable: false, id: 'folder-analytics', name: 'Analytics', parent_id: null, tags: ['ANALYTICS'], sort_order: 4 },
  { is_duplicatable: false, id: 'folder-analytics-reports', name: 'Reports', parent_id: 'folder-analytics', tags: ['REPORTS'], sort_order: 1 },
  { is_duplicatable: false, id: 'folder-analytics-geo', name: 'Geographic Data', parent_id: 'folder-analytics', tags: ['GEO'], sort_order: 2 },

  { is_duplicatable: false, id: 'folder-comms', name: 'Communications', parent_id: null, tags: ['COMMS'], sort_order: 5 },
  { is_duplicatable: false, id: 'folder-tasks', name: 'Tasks', parent_id: null, tags: ['TASKS'], sort_order: 6 },
  { is_duplicatable: false, id: 'folder-settings', name: 'Settings & Admin', parent_id: null, tags: ['ADMIN'], sort_order: 7 },
]

export const SEED_ITEMS: Item[] = [
  {
    id: 'item-adm-001',
    title: 'Application form renders all fields correctly',
    folder_id: 'folder-adm-forms',
    description: `## Steps\n1. Open application form for undergraduate program\n2. Check all required fields are visible\n3. Verify field validation triggers on submit\n\n## Expected Result\nAll fields render, required fields show validation errors when empty.\n\n## Labels\n\`regression\` \`E2E\``,
    tags: ['regression', 'E2E'],
    priority: 'high',
    status: 'Done',
    tickets: [{ key: 'ET-9100', url: 'https://example.atlassian.net/browse/ET-9100' }],
    bugs: [],
    is_stable: true,
    is_duplicatable: false,
  },
  {
    id: 'item-adm-002',
    title: 'Auto-assign gender based on relationship when field is absent',
    folder_id: 'folder-adm-forms',
    description: `## Steps\n1. Create signup form without gender field\n2. Set relationship to "Mother"\n3. Submit form\n\n## Expected Result\nGender is auto-set to "Female" based on relationship type.\n\n## Notes\nSee ET-9343 for original bug report.`,
    tags: ['regression'],
    priority: 'medium',
    status: 'Done',
    tickets: [{ key: 'ET-9343' }],
    bugs: [],
    is_stable: true,
    is_duplicatable: false,
  },
  {
    id: 'item-adm-003',
    title: 'Stage transitions respect permission rules',
    folder_id: 'folder-adm-workflow',
    description: `## Steps\n1. Log in as agent (non-admin)\n2. Try to move application from Offer → Enrolled\n3. Verify permission check fires\n\n## Expected Result\nAgent cannot skip stages; admin override works correctly.`,
    tags: ['permissions', 'regression'],
    priority: 'critical',
    status: 'To Do',
    tickets: [],
    bugs: [{ key: 'BUG-441' }],
    is_stable: false,
    is_duplicatable: false,
  },

  {
    id: 'item-events-001',
    title: 'Event registration form submits successfully',
    folder_id: 'folder-events-reg',
    description: `## Steps\n1. Open public event registration page\n2. Fill in all required fields\n3. Click Register\n\n## Expected Result\nConfirmation email sent, attendee appears in event dashboard.`,
    tags: ['E2E', 'regression'],
    priority: 'high',
    status: 'Done',
    tickets: [{ key: 'ET-8751' }],
    bugs: [],
    is_stable: true,
    is_duplicatable: false,
  },
  {
    id: 'item-events-002',
    title: 'Event-specific email templates render correct placeholders',
    folder_id: 'folder-events-email',
    description: `## Steps\n1. Create event with custom email template\n2. Register a test attendee\n3. Check received email\n\n## Expected Result\n{{event_name}}, {{date}}, {{location}} all populate correctly.`,
    tags: ['EMAIL', 'regression'],
    priority: 'medium',
    status: 'Done',
    tickets: [{ key: 'ET-9437' }],
    bugs: [],
    is_stable: true,
    is_duplicatable: false,
  },

  {
    id: 'item-crm-001',
    title: 'Contact merge deduplicates records correctly',
    folder_id: 'folder-crm-contacts',
    description: `## Steps\n1. Create two contacts with same email\n2. Run merge wizard\n3. Select master record\n\n## Expected Result\nDuplicate removed, all history preserved on master record.`,
    tags: ['regression', 'data-integrity'],
    priority: 'high',
    status: 'In Progress',
    tickets: [],
    bugs: [{ key: 'BUG-512' }],
    is_stable: false,
    is_duplicatable: false,
  },
  {
    id: 'item-crm-002',
    title: 'Lead score updates on status change',
    folder_id: 'folder-crm-pipeline',
    description: `## Steps\n1. Open a lead in pipeline\n2. Change status from "Prospect" to "Qualified"\n3. Check score panel\n\n## Expected Result\nScore increases by configured delta within 5 seconds.`,
    tags: ['regression'],
    priority: 'medium',
    status: 'To Do',
    tickets: [{ key: 'ET-9200' }],
    bugs: [],
    is_stable: false,
    is_duplicatable: false,
  },

  {
    id: 'item-analytics-001',
    title: 'Geographic address renders correctly on map',
    folder_id: 'folder-analytics-geo',
    description: `## Steps\n1. Open Analytics > Geographic view\n2. Filter by last 30 days\n3. Hover over a data point\n\n## Expected Result\nAddress tooltip shows full formatted address, map pin is accurate.`,
    tags: ['regression'],
    priority: 'medium',
    status: 'Done',
    tickets: [{ key: 'ET-9334' }],
    bugs: [],
    is_stable: true,
    is_duplicatable: false,
  },
  {
    id: 'item-analytics-002',
    title: 'Conversion funnel report exports to CSV',
    folder_id: 'folder-analytics-reports',
    description: `## Steps\n1. Open Reports > Conversion Funnel\n2. Set date range and click Export CSV\n3. Open downloaded file\n\n## Expected Result\nCSV contains all funnel stages with correct counts and percentages.`,
    tags: ['E2E'],
    priority: 'low',
    status: 'To Do',
    tickets: [],
    bugs: [],
    is_stable: false,
    is_duplicatable: false,
  },

  {
    id: 'item-comms-001',
    title: 'Bulk SMS respects opt-out list',
    folder_id: 'folder-comms',
    description: `## Steps\n1. Add a contact to opt-out list\n2. Send bulk SMS campaign targeting their segment\n3. Check delivery logs\n\n## Expected Result\nOpt-out contact receives 0 messages; all others receive correctly.`,
    tags: ['compliance', 'regression'],
    priority: 'critical',
    status: 'Done',
    tickets: [{ key: 'ET-8933' }],
    bugs: [],
    is_stable: true,
    is_duplicatable: false,
  },

  {
    id: 'item-tasks-001',
    title: 'Task assignment sends notification to assignee',
    folder_id: 'folder-tasks',
    description: `## Steps\n1. Create a task and assign to user B\n2. User B checks notifications\n\n## Expected Result\nIn-app notification and email both arrive within 1 minute.`,
    tags: ['notifications', 'regression'],
    priority: 'medium',
    status: 'To Do',
    tickets: [],
    bugs: [],
    is_stable: false,
    is_duplicatable: false,
  },
]

export const SEED_RELEASES: Release[] = [
  {
    id: 'release-26-2-0',
    name: 'Release 26.2.0',
    date: '2026-03-31',
    affected_folder_ids: ['folder-events', 'folder-events-reg', 'folder-events-email', 'folder-analytics', 'folder-analytics-geo', 'folder-comms'],
    affected_item_ids: ['item-events-001', 'item-events-002', 'item-analytics-001', 'item-comms-001'],
    excluded_folder_ids: [],
    tags: ['EVENTS', 'ANALYTICS', 'COMMS'],
  },
  {
    id: 'release-26-3-0',
    name: 'Release 26.3.0',
    date: '2026-04-28',
    affected_folder_ids: ['folder-admissions', 'folder-adm-forms', 'folder-crm', 'folder-crm-contacts'],
    affected_item_ids: ['item-adm-001', 'item-adm-002', 'item-crm-001'],
    excluded_folder_ids: [],
    tags: ['ADMISSIONS', 'CRM'],
  },
]
